-- Better Auth tables (generated by @better-auth/cli against the configured plugins)
create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" integer not null, "image" text, "createdAt" date not null, "updatedAt" date not null);

create table "session" ("id" text not null primary key, "expiresAt" date not null, "token" text not null unique, "createdAt" date not null, "updatedAt" date not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" date, "refreshTokenExpiresAt" date, "scope" text, "password" text, "createdAt" date not null, "updatedAt" date not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" date not null, "createdAt" date not null, "updatedAt" date not null);

create table "apikey" ("id" text not null primary key, "configId" text not null, "name" text, "start" text, "referenceId" text not null, "prefix" text, "key" text not null, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" date, "enabled" integer, "rateLimitEnabled" integer, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" date, "expiresAt" date, "createdAt" date not null, "updatedAt" date not null, "permissions" text, "metadata" text);

create table "deviceCode" ("id" text not null primary key, "deviceCode" text not null, "userCode" text not null, "userId" text, "expiresAt" date not null, "status" text not null, "lastPolledAt" date, "pollingInterval" integer, "clientId" text, "scope" text);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create index "apikey_configId_idx" on "apikey" ("configId");

create index "apikey_referenceId_idx" on "apikey" ("referenceId");

create index "apikey_key_idx" on "apikey" ("key");
-- Folio tables
create table "document" (
  "id" text not null primary key,
  "ownerId" text not null references "user" ("id") on delete cascade,
  "title" text not null,
  "visibility" text not null default 'private' check ("visibility" in ('private', 'unlisted', 'public')),
  "source" text not null,
  "html" text not null,
  "meta" text not null,
  "version" integer not null default 1,
  "createdAt" text not null,
  "updatedAt" text not null
);
create index "document_ownerId_updatedAt_idx" on "document" ("ownerId", "updatedAt" desc);

create table "comment" (
  "id" text not null primary key,
  "documentId" text not null references "document" ("id") on delete cascade,
  "authorId" text not null references "user" ("id") on delete cascade,
  "blockId" text,
  "body" text not null,
  "resolved" integer not null default 0,
  "createdAt" text not null,
  "updatedAt" text not null
);
create index "comment_documentId_idx" on "comment" ("documentId");
